### ISSUE TITLE
Terceira Avaliação por Pares

### ISSUE THREAD

**Issue by mileneserrano** [UnBArqDsw2021-2/2021.2_G4_CadernetaDeCampoDigital_docs#131]
Olá Pessoal!

O Grupo 04 irá avaliar o Grupo 06 nessa terceira avaliação por pares.
Os templates, em doc ou pdf, e demais informações para essa avaliação constam disponíveis no Moodle.
Basta acessar o Tópico 2 DSW(Padrões de Software) no Moodle, e procurar por "Terceira Avaliação por Pares".

Deadline: 25 de Março de 2022, ao final do dia, conforme consta no cronograma.

Atenciosamente.

**Comment by Joao-Moura** [comment]
Feito
