### ISSUE TITLE
Criação do Product Backlog

### ISSUE THREAD

**Issue by brenno-silva** [UnBArqDsw2021-2/2021.2_G4_CadernetaDeCampoDigital_docs#45]
## Descrição da Issue
Criação do Product Backlog

## Tasks:
- [x] Criar documento
- [x] Priorizar

**Comment by oEduardoAfonso** [comment]
![pbb](https://user-images.githubusercontent.com/54921791/153761163-f3955b56-577d-4403-aa56-17fabf5f6b6e.jpg)
