### ISSUE TITLE
Criação do  DER (Diagrama Entidade-Relacionamento)

### ISSUE THREAD

**Issue by RcleydsonR** [UnBArqDsw2021-2/2021.2_G4_CadernetaDeCampoDigital_docs#60]
## Descrição da Issue

Issue destinada a criar e documentar o diagrama de entidade-relacionamento

## Tasks:
- [x] Criar diagrama
- [x] Documentar diagrama
- [x] Fazer Introdução

**Comment by thiagohdaqw** [comment]
## Arquivos

Os arquivos dos diagramas podem ser encontrados aqui
https://drive.google.com/drive/folders/1ApMzqo6fHotvqu1GEdWTGywz_iyP3EWH?usp=sharing

**Comment by Joao-Moura** [comment]
Completo
