### ISSUE TITLE
Criação do diagrama de causa e efeito

### ISSUE THREAD

**Issue by Denniel-sudo** [UnBArqDsw2021-2/2021.2_G4_CadernetaDeCampoDigital_docs#8]
## Descrição da Issue
Criação do documento de causa e efeito (diagrama de ishikawa)

## Tasks:
- [x] Criação do documento
- [x] Adicionar metodologia
- [x] Adicionar diagrama

## Critérios de Aceitação:
- [x] Documento criado

**Comment by Joao-Moura** [comment]
Feito
