### ISSUE TITLE
Documentar Padrões de Projetos Emergentes

### ISSUE THREAD

**Issue by VitorLamego** [UnBArqDsw2021-2/2021.2_G4_CadernetaDeCampoDigital_docs#92]
## Descrição da Issue
Realizar estudo e documentação dos padrões de projetos emergentes em engenharia de software.

## Tasks:
- [x] Realizar Estudo
- [x] Documentar resultados obtidos

## Critérios de Aceitação:
- [x] Documentar na Wiki

**Comment by Joao-Moura** [comment]
Feito
