### ISSUE TITLE
Documentar estudo sobre GoFs Estruturais

### ISSUE THREAD

**Issue by oEduardoAfonso** [UnBArqDsw2021-2/2021.2_G4_CadernetaDeCampoDigital_docs#97]
## Descrição da Issue

Estudar e documentar parte teórica do GoFs estruturais

## Tasks:
- [x] Estudar GoFs estruturais
- [x] Documentar o estudo

## Critérios de Aceitação:
- [x] Página para documentar o estudo criada na wiki

**Comment by Joao-Moura** [comment]
Completo
